site:
  title: Redpanda Docs
  start_page: redpanda-labs:ROOT:index.adoc
  url: http://localhost:5002
  robots: disallow
  keys:
    preview: true
urls:
  html_extension_style: indexify
  latest_version_segment: 'current'
output:
  clean: true
content:
  sources:
  - url: ../../docs
    branches: HEAD
  - url: https://github.com/redpanda-data/documentation
    branches: [v/*, api, site-search]
  - url: ../
    branches: HEAD
    start_paths: [docs,'*/docs']
  - url: ../../shared-docs
    branches: HEAD
ui:
  bundle:
    url: ../../docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - '@redpanda-data/docs-extensions-and-macros/macros/glossary'
  - '@redpanda-data/docs-extensions-and-macros/macros/config-ref'
  - '@redpanda-data/docs-extensions-and-macros/macros/helm-ref'
  - '@redpanda-data/docs-extensions-and-macros/asciidoc-extensions/add-line-numbers-highlights'
antora:
  extensions:
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/replace-attributes-in-attachments'
  - require: '../../docs-extensions-and-macros/extensions/unlisted-pages'
  - require: '../../docs-extensions-and-macros/extensions/add-global-attributes'
  - '../../docs-extensions-and-macros/extensions/version-fetcher/set-latest-version'
  - require: '../../docs-extensions-and-macros/extensions/validate-attributes'
  - require: '../../docs-extensions-and-macros/extensions/find-related-docs'
  - require: '../../docs-extensions-and-macros/extensions/find-related-labs'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/aggregate-terms'

